version: '3.1'
services:
   webserver:
    image: nginx:latest
    container_name: nginx_webserver
    ports:
       - "8089:80"
    networks:
    - app_network
   db:
     image: mysql:latest
     container_name: mysql_db
     restart: unless-stopped
     networks:
     - app_network     
     volumes:
       - db_vol:/var/lib/mysql
     environment:
       MYSQL_ROOT_PASSWORD: ${root_password}
       MYSQL_DATABASE: ${db_name}
       MYSQL_USER: ${user}
       MYSQL_PASSWORD: ${password}

volumes:
    db_vol:

networks:
  app_network: